### ISSUE TITLE
getDatapoints empty

### ISSUE THREAD

**Issue by stefano055415** [bobaos/bdsd-cli#1]
I'm trying to use bdsd-cli, I installed the bdsd.sock service correctly, I connect, but with getDatapoints I always get an empty array and then I can not send any commands

**Comment by shabunin** [comment]
The only case I get an empty array is when there is no configured and downloaded datapoints to BAOS 838 module. Make sure you configure it correctly. 

Here I replayed my case: https://youtu.be/n2tHf7tlhUA

Otherwise try to reboot raspberry pi

**Comment by stefano055415** [comment]
but is it possible to monitor the group addresses of the bus? 
I would like to use the kberry to monitor the addresses and use it to program the other devices

**Comment by shabunin** [comment]
Bobaos project is suited just for working with BAOS ObjectServer protocol for accessing datapoint objects. It is convenient to work with data due to auto dpt conversion between raw bytes from KNX but and js values. If you want to use BAOS as an IP router then take a look at knxd project.
